// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3sC1oRIDTBN9x68LG_mljqnTjvIcmHJ0',
    appId: '1:129934098142:web:6734775583245fe96d0c4f',
    messagingSenderId: '129934098142',
    projectId: 'device-streaming-9a1a3527',
    authDomain: 'device-streaming-9a1a3527.firebaseapp.com',
    storageBucket: 'device-streaming-9a1a3527.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ9vWT1-vlpqIAfDp0FXh9hYt9BndlBVE',
    appId: '1:129934098142:android:4e5a5b4d3128a1a26d0c4f',
    messagingSenderId: '129934098142',
    projectId: 'device-streaming-9a1a3527',
    storageBucket: 'device-streaming-9a1a3527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAiHKBUg1c5V6wVeo_Gkzf5jkYUkSsRG0',
    appId: '1:129934098142:ios:ad15577e04ab53966d0c4f',
    messagingSenderId: '129934098142',
    projectId: 'device-streaming-9a1a3527',
    storageBucket: 'device-streaming-9a1a3527.firebasestorage.app',
    iosBundleId: 'com.example.banxe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAiHKBUg1c5V6wVeo_Gkzf5jkYUkSsRG0',
    appId: '1:129934098142:ios:ad15577e04ab53966d0c4f',
    messagingSenderId: '129934098142',
    projectId: 'device-streaming-9a1a3527',
    storageBucket: 'device-streaming-9a1a3527.firebasestorage.app',
    iosBundleId: 'com.example.banxe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3sC1oRIDTBN9x68LG_mljqnTjvIcmHJ0',
    appId: '1:129934098142:web:35c6df0403cd1af16d0c4f',
    messagingSenderId: '129934098142',
    projectId: 'device-streaming-9a1a3527',
    authDomain: 'device-streaming-9a1a3527.firebaseapp.com',
    storageBucket: 'device-streaming-9a1a3527.firebasestorage.app',
  );

}